### ISSUE TITLE
Error in rule splitting 

### ISSUE THREAD

**Issue by allychamp** [samnooij/PathoFact#3]
Hi, I have problems running the test files. Everytime I run it,  have this error: 

[Thu Aug  8 15:58:49 2024]
Job 42: Execute classifier for virulence factor prediction on the following sample(s): output_test - test_sample
Reason: Missing output files: test/output_test/PathoFact_intermediate/VIRULENCE/classifier_virulence/test_sample/group_1_classifier_prediction.tsv; Input files updated by another job: test/output_test/PathoFact_intermediate/VIRULENCE/classifier_virulence/test_sample/group_1_matrix.tsv

python scripts/virulence_prediction.py test/output_test/PathoFact_intermediate/VIRULENCE/classifier_virulence/test_sample/group_1_matrix.tsv test/output_test/PathoFact_intermediate/VIRULENCE/classifier_virulence/test_sample/group_1_classifier_prediction.tsv scripts/Virulence_factor_model.sav &> test/output_test/logs/test_sample/group_1_classifier_prediction.log
Activating conda environment: /home/champa/PathoFact/.snakemake/conda/1f0c605d
Activating conda environment: /home/champa/PathoFact/.snakemake/conda/7da68472
Activating conda environment: /home/champa/PathoFact/.snakemake/conda/7da68472
Updating job 22.
Updating job 23.
Creating conda environment envs/rgi.yaml...
Downloading remote packages.
Environment for envs/rgi.yaml created (location: .snakemake/conda/9dc4e991)
Creating conda environment envs/DeepARG.yaml...
Downloading remote packages.
[Thu Aug  8 15:59:21 2024]
Error in rule splitting:
    jobid: 31
    output: test/output_test/PathoFact_intermediate/splitted/test_sample/
    log: test/output_test/PathoFact_intermediate/logs/test_sample/split_ORF.log (check log file(s) for error message)
    conda-env: /home/champa/PathoFact/.snakemake/conda/7da68472
    shell:
        
        python scripts/split.py test/output_test/PathoFact_intermediate/PathoFact_intermediate/renamed/test_sample_ID.faa 10000 test/output_test/PathoFact_intermediate/splitted/test_sample/ &> test/output_test/PathoFact_intermediate/logs/test_sample/split_ORF.log
        
        (exited with non-zero exit code)

[Thu Aug  8 15:59:21 2024]
Finished job 3.
5 of 25 steps (20%) done
Removing temporary output file test/output_test/PathoFact_intermediate/VIRULENCE/classifier_virulence/test_sample/group_1_matrix.tsv.
[Thu Aug  8 15:59:21 2024]
Finished job 42.
6 of 25 steps (24%) done
Removing output files of failed job splitting since they might be corrupted:
test/output_test/PathoFact_intermediate/splitted/test_sample/
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/champa/PathoFact/.snakemake/log/2024-08-08T155848.735372.snakemake.log

[split_ORF.log](https://github.com/user-attachments/files/16553010/split_ORF.log)

This is the command I use : 
snakemake -s test/Snakefile --use-conda --reason --cores -p -w 30

I checked all dependencies and they do not seem to be the problem. Can you help me please, I have been on that for at least a week and I don't know what to do anymore.

Thank you :)

**Comment by samnooij** [comment]
Please refer to the original repository at https://gitlab.lcsb.uni.lu/laura.denies/PathoFact 
This repository is a fork and little personal hobby project that is not supported and no longer maintained. Sorry!
