### ISSUE TITLE
 Reducing Virulence Factor Output: Thresholds and Filtering Options?

### ISSUE THREAD

**Issue by redlou-del** [samnooij/PathoFact#4]
Hi,

Thank you very much for developing PathoFact, it's proving to be a very useful tool for my research. I have a question regarding the output of the Virulence (`Vir`) module.

I'm currently running the Virulence (`Vir`) analysis on my dataset, but the output is producing a large number of virulence factor results, many of which seem to be low-confidence predictions. I'm trying to reduce the number of false positives and get only high-confidence virulence factors in the final output.

I have examined the config.yaml and the Snakemake rules in Virulence.smk, but I couldn't find any direct parameter (such as a threshold for HMM scanning or filtering) that might help me reduce the number of virulence factors being predicted.

Any suggestions on how to proceed in adjusting the Virulence module output would be greatly appreciated.

Thanks in advance for your support!

Best regards,
Gru

**Comment by samnooij** [comment]
Dear Gru,

Thank you for your message and I am happy that PathoFact has been useful for you. However, I have not been involved with the development and am in no way affiliated with PathoFact. Please refer to the original project repository at https://git-r3lab.uni.lu/laura.denies/PathoFact.

Good luck!
